# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7edaa3987c06ddbd0798b81d4ace291bff54fd873d56ccdd54f3ba9088adf15d8afd7861bfb448c933e15947aab3953d941cfe72eae46ea84e63403b38e0da3

test:
  secret_key_base: a2751e5a7b4eeda495abbf47fe19de90e12b1299ae598a7c6228f29c1389be7981bc1c4af111961357c639dccb7318e365b8302949a6c7d7f2945c07e1607ea5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
